Repository puppetlabs/puppetlabs-websphere_application_server, pull requests merged in 2019-04, with the labels that each got.

#165 pdksync - (MODULES-8444) - Raise lower Puppet bound
  metadata.json
Labels: backwards-incompatible

#162 Modules 7472 - Websphere_application_server: Instance installation fails with nil conversion
  README.md
Labels: bugfix

#166 pdksync - (maint) Update pdk-template to f778803
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  metadata.json
Labels: maintenance
