Repository puppetlabs/puppetlabs-websphere_application_server, pull requests merged in 2023-01, with the labels that each got.

#255 (GH-254) Restore integration rake task
  Rakefile
Labels: maintenance

#249 Fix was files ownership
  manifests/instance.pp
Labels: community

#250 Add conditional appserver systemctl
  manifests/profile/appserver.pp
Labels: feature, community

#256 Fix complaints about title patterns using procs being not supported
  lib/puppet/type/websphere_jvm_log.rb
  lib/puppet/type/websphere_sdk.rb
Labels: bugfix, community

#257 Fix generic jvm args
  lib/puppet/provider/websphere_cluster_member/wsadmin.rb
Labels: bugfix, community

#252 Fix websphere variable type
  lib/puppet/provider/websphere_variable/wsadmin.rb
  lib/puppet/type/websphere_variable.rb
Labels: bugfix, community

#251 Add admin security profile creation options
  manifests/profile/appserver.pp
  manifests/profile/dmgr.pp
Labels: bugfix, community
